# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  bibata-modern-ice = {
    pname = "bibata-modern-ice";
    version = "2.0.7";
    src = fetchurl {
      url = "https://github.com/ful1e5/Bibata_Cursor/releases/download/v2.0.7/Bibata-Modern-Ice.tar.xz";
      sha256 = "sha256-poyuYMTccGNQ4ZTryRxf5IvHvJ1Z4RlVWDSip+5QeO8=";
    };
  };
  darkly-gtk = {
    pname = "darkly-gtk";
    version = "36d24ba0fed2b5274cfe28100a3104465fb69516";
    src = fetchFromGitHub {
      owner = "wrymt";
      repo = "darkly-gtk";
      rev = "36d24ba0fed2b5274cfe28100a3104465fb69516";
      fetchSubmodules = false;
      sha256 = "sha256-9qJ/nKXNXbX9e7iUt906gxordEU4VMXhq5Vhs9uQ7b8=";
    };
  };
  dwproton = {
    pname = "dwproton";
    version = "dwproton-11.0-13";
    src = fetchurl {
      url = "https://dawn.wine/dawn-winery/dwproton/releases/download/dwproton-11.0-13/dwproton-11.0-13-x86_64.tar.xz";
      sha256 = "sha256-lMkSsyBeH5o7lmFOo9w5+jVCETIB4G44LbD3w8XSQfQ=";
    };
  };
  genoffice = {
    pname = "genoffice";
    version = "0.11.0";
    src = fetchurl {
      url = "https://github.com/genspark-ai/genoffice/releases/download/v0.11.0/GenOffice-0.11.0.AppImage";
      sha256 = "sha256-iYKCjYfFFe4YzfezxahhCbwMl+FvkBkogZGSnhxOQWw=";
    };
  };
  kelivo = {
    pname = "kelivo";
    version = "v1.2.6+73";
    src = fetchurl {
      url = "https://github.com/Chevey339/kelivo/releases/download/v1.2.6/Kelivo_linux_1.2.6%2B73.tar.gz";
      sha256 = "sha256-QTG/BuYbsarMAzy/ktGljiEE2GY6h4iJvDdt1EavS8U=";
    };
  };
  wechat = {
    pname = "wechat";
    version = "4.1.13";
    src = fetchurl {
      url = "https://dldir1v6.qq.com/weixin/Universal/Linux/WeChatLinux_x86_64.AppImage";
      sha256 = "sha256-T1StKQLs1vb9xWgLc1R/gNVCO/RwsBI3pXmi5bPK7us=";
    };
  };
  zedg = {
    pname = "zedg";
    version = "v1.21.0";
    src = fetchurl {
      url = "https://github.com/WenYin-Community/zed-globalization/releases/download/v1.21.0/zedg-zh-cn-linux-x86_64-v1.21.0.tar.gz";
      sha256 = "sha256-2tkCTgXH4/bg5UjwnVqmLrHbO3BIw+nyCxQRKpa6hlA=";
    };
  };
}
