# 浏览器：Zen（Firefox 分支）+ Pywalfox 联动。
{
  pkgs,
  lib,
  inputs,
  ...
}:

let
  # Pywalfox 的 native messaging 清单。nixpkgs 的 pywalfox-native 只装 Python
  # 包，不含浏览器读取的 lib/mozilla/native-messaging-hosts/pywalfox.json，
  # 所以这里生成一份，交给 Zen 的 wrapFirefox（nativeMessagingHosts）在启动时
  # 软链到 ~/.mozilla/native-messaging-hosts（Gecko/Zen 固定读取该目录）。
  # path 指向 pywalfox 可执行文件：Firefox 传参时其 __main__ 会走兼容分支启动守护进程。
  pywalfoxNativeHost = pkgs.runCommand "pywalfox-native-messaging-host" { } ''
    mkdir -p $out/lib/mozilla/native-messaging-hosts
    cat > $out/lib/mozilla/native-messaging-hosts/pywalfox.json <<'EOF'
    {
      "name": "pywalfox",
      "description": "Automatically theme your browser using the colors generated by Pywal",
      "path": "${lib.getExe pkgs.pywalfox-native}",
      "type": "stdio",
      "allowed_extensions": [ "pywalfox@frewacom.org" ]
    }
    EOF
  '';

  # 注：Pywalfox 的 ~/.cache/wal/colors.json -> dank-pywalfox.json 软链
  # 不由 home-manager 声明，因为目标（dank-pywalfox.json）是 DMS 在运行时
  # 才生成的，声明式激活会在目标缺失时产生悬空软链/激活失败。
  # 改由 modules/nixos/desktop/dms.nix 的 pywalfox-colors 用户服务在
  # DMS 写出调色板后创建并刷新。
in
{
  home.packages = [
    # Pywalfox：与 Zen 的 Pywalfox 扩展配合。配色由 DMS 生成到
    # ~/.cache/wal/dank-pywalfox.json，用户服务把它接到扩展固定读取的
    # ~/.cache/wal/colors.json。
    pkgs.pywalfox-native

    # Zen Browser（Firefox 分支）。挂上 Pywalfox 的 native messaging 清单，
    # 启动时自动软链到 ~/.mozilla/native-messaging-hosts，消除
    # “No such native application pywalfox” 报错。
    (inputs.zen-browser.packages.${pkgs.stdenv.hostPlatform.system}.beta.override {
      nativeMessagingHosts = [ pywalfoxNativeHost ];
    })
  ];
}
